name: Bitmono
markdown: redcarpet
pygments: true
host: 0.0.0.0
port: 4000
baseurl: /
# url: http://localhost:4000

# paginate: 10
# paginate_path: "blog/page:num"

exclude: [CNAME, Gemfile, Gemfile.lock, LICENSE, README.md]

sass:
    style: compact  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)

    compile_in_place: false   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory